version: '3.7'

services:

  db:
    container_name: postgres_container
    image: postgres
    ports:
    - "5432:5432"
    networks:
      - postgres
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data
      - ./data/postgres/pgconf:/etc/postgresql
      - ./data/postgres/pglog:/var/log/postgresql
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: luke@valkyriweb.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
       - ./data/pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local